# Generated by Django 3.2.6 on 2021-08-26 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('ano_de_matricula', models.IntegerField()),
            ],
        ),
    ]
